"""Base Strategy class for all trading strategies"""

import collections
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Deque, List, Optional, Dict, Any, Tuple

from ..utils.market_utils import get_mid_price, round_to_tick


@dataclass
class Signal:
    """Trading signal generated by a strategy"""
    market_id: str
    outcome: str  # "YES" or "NO"
    action: str   # "BUY" or "SELL"
    confidence: float  # 0.0 to 1.0
    price: float
    size: float
    reason: str = ""  # Explanation for the signal


class Strategy(ABC):
    """
    Abstract base class for all trading strategies.

    All strategies must inherit from this class and implement
    the analyze() and should_enter() methods.
    """

    def __init__(self, name: str, config: Dict[str, Any]):
        self.name = name
        self.config = config
        self.enabled = config.get("enabled", True)
        self.min_confidence = config.get("min_confidence", 0.5)
        self.max_position_size = config.get("max_position_size", 1000.0)
        self.max_entry_price = config.get("max_entry_price", 0.95)
        self.min_entry_price = config.get("min_entry_price", 0.05)
        self.exit_rule: str = config.get("exit_rule", "default")
        self.last_skip_reason: str = ""

        # Position state — authoritative after sync_position_from_inventory()
        self.active_token_id: Optional[str] = None
        self.entry_price: Optional[float] = None
        self.entry_timestamp: Optional[float] = None
        self.entry_size: Optional[float] = None

        # Token context — subclasses populate via set_tokens()
        self._market_id: str = ""
        self._outcome_map: Dict[str, str] = {}
        self._yes_token_id: str = ""
        self._no_token_id: str = ""

        # Mid-price history: token_id → deque of (monotonic_ts, mid)
        # deque allows O(1) front-trim vs O(n) list comprehension rebuild
        self._price_history: Dict[str, Deque[Tuple[float, float]]] = {}
        self._history_max_age: float = 300.0

        # Pending exit info for PnL computation
        self._pending_exit_entry_price: Optional[float] = None
        self._pending_exit_entry_size: Optional[float] = None

    @abstractmethod
    def analyze(self, market_data: Dict[str, Any]) -> List[Signal]:
        pass

    @abstractmethod
    def should_enter(self, signal: Signal) -> bool:
        pass

    def should_exit(self, position: Dict[str, Any], market_data: Dict[str, Any]) -> bool:
        return False

    def calculate_position_size(
        self,
        signal: Signal,
        balance: float,
        current_positions: List[Dict[str, Any]]
    ) -> float:
        size = min(signal.size, self.max_position_size)
        max_by_balance = balance * self.config.get("max_position_pct", 0.1)
        size = min(size, max_by_balance)
        return max(0.0, size)

    def validate_signal(self, signal: Signal) -> bool:
        if not self.enabled:
            return False
        if signal.confidence < self.min_confidence:
            return False
        if signal.price < 0.0 or signal.price > 1.0:
            return False
        if signal.size <= 0.0:
            return False
        if signal.action not in ["BUY", "SELL"]:
            return False
        if signal.outcome not in ["YES", "NO"]:
            return False
        return True

    # ------------------------------------------------------------------
    # Token context and price history
    # ------------------------------------------------------------------

    def set_tokens(self, market_id: str, yes_token_id: str, no_token_id: str) -> None:
        """Register current market tokens. Resets position state on rollover."""
        if (yes_token_id != self._yes_token_id or no_token_id != self._no_token_id) \
                and self._yes_token_id:
            self._reset_position_state()
        self._market_id = market_id
        self._yes_token_id = yes_token_id
        self._no_token_id = no_token_id
        self._outcome_map = {yes_token_id: "YES", no_token_id: "NO"}

    def record_price(self, token_id: str, mid: float, ts: Optional[float] = None) -> None:
        """Feed a mid-price observation into the internal history buffer."""
        now = ts if ts is not None else time.monotonic()
        buf = self._price_history.setdefault(token_id, collections.deque())
        buf.append((now, mid))
        cutoff = now - self._history_max_age
        while buf and buf[0][0] < cutoff:
            buf.popleft()

    # ------------------------------------------------------------------
    # Shared position lifecycle helpers
    # ------------------------------------------------------------------

    def check_exit(
        self,
        order_books: Dict[str, Any],
        by_token: Dict[str, Any],
        now_ts: float,
    ) -> Optional[Signal]:
        """
        Common exit logic: take-profit, stop-loss, time-limit.

        Requires the subclass to set on self:
            active_token_id, entry_price, entry_timestamp, entry_size,
            profit_target_pct, stop_loss_pct, max_hold_seconds,
            _market_id, _outcome_map
        """
        if self.exit_rule == "hold_to_expiry":
            return None

        if self.active_token_id is None or self.entry_price is None:
            return None

        pos = by_token.get(self.active_token_id)
        held_size = float(pos.size) if pos and pos.size > 0 else self.entry_size
        if not held_size:
            self._reset_position_state()
            return None

        book = order_books.get(self.active_token_id)
        if book is None:
            return None
        mid = get_mid_price(book)
        best_bid = book.bids[0].price if book.bids else mid
        if not best_bid or best_bid <= 0:
            return None

        profit_pct = (best_bid - self.entry_price) / self.entry_price
        time_held  = now_ts - self.entry_timestamp if self.entry_timestamp else 0.0

        reason: Optional[str] = None
        if profit_pct >= self.profit_target_pct:
            reason = f"take_profit profit={profit_pct:.2%} >= target={self.profit_target_pct:.2%}"
        elif -profit_pct >= self.stop_loss_pct:
            reason = f"stop_loss loss={-profit_pct:.2%} >= limit={self.stop_loss_pct:.2%}"
        elif time_held >= self.max_hold_seconds:
            reason = f"time_limit held={time_held:.0f}s >= max={self.max_hold_seconds}s"

        if reason is None:
            return None

        tick = book.tick_size or 0.001
        return Signal(
            market_id=self._market_id,
            outcome=self._outcome_map.get(self.active_token_id, ""),
            action="SELL",
            confidence=1.0,
            price=round_to_tick(best_bid, tick),
            size=held_size,
            reason=reason,
        )

    def is_flat(self, by_token: Dict[str, Any]) -> bool:
        """True if no position held on either side."""
        for tid in (self._yes_token_id, self._no_token_id):
            if not tid:
                continue
            pos = by_token.get(tid)
            if pos and pos.size > 0:
                return False
        return True

    def _reset_position_state(self) -> None:
        """Reset open position tracking fields to None."""
        self.active_token_id = None
        self.entry_price     = None
        self.entry_timestamp = None
        self.entry_size      = None

    def _auto_recover_position(self, by_token: Dict[str, Any], now_ts: float) -> None:
        """Recover position state from live positions after a bot restart.

        No-op when already tracking a position. Checks YES then NO token.
        """
        if self.active_token_id is not None:
            return
        for tid in (self._yes_token_id, self._no_token_id):
            if not tid:
                continue
            pos = by_token.get(tid)
            if pos and pos.size > 0:
                self.active_token_id = tid
                self.entry_price = pos.average_price
                self.entry_timestamp = now_ts
                self.entry_size = pos.size
                break

    def sync_position_from_inventory(
        self,
        token_id: Optional[str],
        position: float,
        avg_cost: float,
    ) -> None:
        """Synchronize strategy position state with authoritative inventory.

        Called after ExecutionTracker.reconcile() to ensure the strategy's
        internal bookkeeping matches on-chain reality.
        """
        if position > 0 and token_id:
            if self.active_token_id != token_id:
                self.active_token_id = token_id
                self.entry_price = avg_cost
                self.entry_size = position
                self.entry_timestamp = time.monotonic()
        elif self.active_token_id == token_id or token_id is None:
            self._reset_position_state()

    def get_position_info(self) -> Optional[Dict[str, Any]]:
        """Return current open position info for display, or None if flat."""
        if self.active_token_id is None or self.entry_price is None:
            return None
        return {
            "outcome": self._outcome_map.get(self.active_token_id, ""),
            "entry_price": self.entry_price,
            "entry_size": self.entry_size or 0.0,
            "entry_timestamp": self.entry_timestamp or time.monotonic(),
            "max_hold_seconds": self.max_hold_seconds,
        }
