"""Base Strategy class for all trading strategies"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import List, Optional, Dict, Any


@dataclass
class Signal:
    """Trading signal generated by a strategy"""
    market_id: str
    outcome: str  # "YES" or "NO"
    action: str   # "BUY" or "SELL"
    confidence: float  # 0.0 to 1.0
    price: float
    size: float
    reason: str = ""  # Explanation for the signal


class Strategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    All strategies must inherit from this class and implement
    the analyze() and should_enter() methods.
    """
    
    def __init__(self, name: str, config: Dict[str, Any]):
        """
        Initialize strategy
        
        Args:
            name: Strategy name
            config: Strategy-specific configuration dictionary
        """
        self.name = name
        self.config = config
        self.enabled = config.get("enabled", True)
        self.min_confidence = config.get("min_confidence", 0.5)
        self.max_position_size = config.get("max_position_size", 1000.0)
    
    @abstractmethod
    def analyze(self, market_data: Dict[str, Any]) -> List[Signal]:
        """
        Analyze market data and return trading signals
        
        Args:
            market_data: Dictionary containing market information,
                        order book, price history, etc.
                        
        Returns:
            List of Signal objects
        """
        pass
    
    @abstractmethod
    def should_enter(self, signal: Signal) -> bool:
        """
        Determine if we should enter a position based on a signal
        
        Args:
            signal: Trading signal to evaluate
            
        Returns:
            True if we should enter the position
        """
        pass
    
    def should_exit(self, position: Dict[str, Any], market_data: Dict[str, Any]) -> bool:
        """
        Determine if we should exit a position (optional override)
        
        Args:
            position: Current position information
            market_data: Current market data
            
        Returns:
            True if we should exit the position
        """
        return False
    
    def calculate_position_size(
        self,
        signal: Signal,
        balance: float,
        current_positions: List[Dict[str, Any]]
    ) -> float:
        """
        Calculate position size for a signal
        
        Args:
            signal: Trading signal
            balance: Current account balance
            current_positions: List of current positions
            
        Returns:
            Position size to use
        """
        # Default: Use signal size, but cap at max_position_size and available balance
        size = min(signal.size, self.max_position_size)
        
        # Check available balance
        max_by_balance = balance * self.config.get("max_position_pct", 0.1)  # 10% default
        size = min(size, max_by_balance)
        
        return max(0.0, size)
    
    def validate_signal(self, signal: Signal) -> bool:
        """
        Validate a signal before execution
        
        Args:
            signal: Signal to validate
            
        Returns:
            True if signal is valid
        """
        if not self.enabled:
            return False
        
        if signal.confidence < self.min_confidence:
            return False
        
        if signal.price < 0.0 or signal.price > 1.0:
            return False
        
        if signal.size <= 0.0:
            return False
        
        if signal.action not in ["BUY", "SELL"]:
            return False
        
        if signal.outcome not in ["YES", "NO"]:
            return False
        
        return True

