"""Base classes and result objects for indicator system"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional
import pandas as pd


class SignalType(Enum):
    """Types of signals that indicators can generate"""
    # RSI signals
    OVERBOUGHT = "OVERBOUGHT"
    OVERSOLD = "OVERSOLD"
    
    # FVG signals
    BULL_FVG = "BULL_FVG"
    BEAR_FVG = "BEAR_FVG"
    FVG_MITIGATED = "FVG_MITIGATED"
    BULL_FVG_MITIGATED = "BULL_FVG_MITIGATED"
    BEAR_FVG_MITIGATED = "BEAR_FVG_MITIGATED"
    
    # MA signals
    MA_BULLISH_CROSS = "MA_BULLISH_CROSS"
    MA_BEARISH_CROSS = "MA_BEARISH_CROSS"
    PRICE_ABOVE_MA = "PRICE_ABOVE_MA"
    PRICE_BELOW_MA = "PRICE_BELOW_MA"
    
    # Trend signals
    BULLISH_TREND = "BULLISH_TREND"
    BEARISH_TREND = "BEARISH_TREND"
    SIDEWAYS = "SIDEWAYS"
    
    # Generic
    NEUTRAL = "NEUTRAL"
    CUSTOM = "CUSTOM"


class SignalSeverity(Enum):
    """Severity levels for signals"""
    CRITICAL = "CRITICAL"  # Extreme conditions
    HIGH = "HIGH"          # Strong signals
    MEDIUM = "MEDIUM"      # Moderate signals
    LOW = "LOW"            # Weak signals
    INFO = "INFO"          # Informational only


@dataclass
class Signal:
    """Signal/alert generated by an indicator
    
    Attributes:
        type: Type of signal (from SignalType enum)
        severity: Severity level of the signal
        value: Primary numeric value associated with signal
        message: Human-readable description
        timestamp: Optional timestamp for the signal
        metadata: Additional data about the signal
    """
    type: SignalType
    severity: SignalSeverity
    value: float
    message: str
    timestamp: Optional[pd.Timestamp] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def __str__(self) -> str:
        return f"[{self.severity.value}] {self.type.value}: {self.message} (value={self.value:.2f})"


@dataclass
class IndicatorResult:
    """Result object returned by indicator compute() method
    
    Attributes:
        indicator_name: Name of the indicator
        timeframe: Timeframe the indicator was computed on
        values: Dictionary of computed values (e.g., {'rsi': 45.2, 'period': 14})
        signals: List of signals generated by the indicator
        metadata: Optional additional information (e.g., full record lists)
    """
    indicator_name: str
    timeframe: str
    values: Dict[str, Any]
    signals: List[Signal] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def has_signals(self) -> bool:
        """Check if any signals were generated"""
        return len(self.signals) > 0
    
    def get_signals_by_type(self, signal_type: SignalType) -> List[Signal]:
        """Get all signals of a specific type"""
        return [s for s in self.signals if s.type == signal_type]
    
    def get_signals_by_severity(self, min_severity: SignalSeverity) -> List[Signal]:
        """Get signals at or above a severity level"""
        severity_order = {
            SignalSeverity.INFO: 0,
            SignalSeverity.LOW: 1,
            SignalSeverity.MEDIUM: 2,
            SignalSeverity.HIGH: 3,
            SignalSeverity.CRITICAL: 4,
        }
        min_level = severity_order[min_severity]
        return [s for s in self.signals if severity_order[s.severity] >= min_level]
    
    def __str__(self) -> str:
        signal_summary = f"{len(self.signals)} signals" if self.signals else "no signals"
        return f"{self.indicator_name} ({self.timeframe}): {signal_summary}"


@dataclass
class IndicatorConfig:
    """Configuration for an indicator
    
    Attributes:
        name: Name of the indicator
        params: Dictionary of parameters specific to the indicator
    """
    name: str
    params: Dict[str, Any] = field(default_factory=dict)


class Indicator(ABC):
    """Base class for all technical indicators
    
    All indicators must inherit from this class and implement the compute() method.
    Indicators should be stateless and thread-safe - all state should be in the config.
    
    Example:
        >>> config = IndicatorConfig(name="RSI", params={"period": 14})
        >>> indicator = RSIIndicator(config)
        >>> result = indicator.compute(ohlc_data, timeframe="1h")
        >>> print(result.values['rsi'])
        45.2
    """
    
    def __init__(self, config: IndicatorConfig):
        """Initialize indicator with configuration
        
        Args:
            config: IndicatorConfig with name and parameters
        """
        self.name = config.name
        self.params = config.params
    
    @abstractmethod
    def compute(self, ohlc: pd.DataFrame, timeframe: str = "unknown") -> IndicatorResult:
        """Compute indicator values and generate signals
        
        Args:
            ohlc: DataFrame with columns 'open', 'high', 'low', 'close'
                  Index should be DatetimeIndex when possible
            timeframe: String identifier for the timeframe (e.g., "1h", "5m")
        
        Returns:
            IndicatorResult containing computed values and signals
        """
        pass
    
    def validate_ohlc(self, ohlc: pd.DataFrame) -> bool:
        """Validate that OHLC DataFrame has required columns
        
        Args:
            ohlc: DataFrame to validate
            
        Returns:
            True if valid, raises ValueError if not
        """
        required_cols = ['open', 'high', 'low', 'close']
        missing = [col for col in required_cols if col not in ohlc.columns]
        
        if missing:
            raise ValueError(f"OHLC DataFrame missing required columns: {missing}")
        
        if len(ohlc) == 0:
            raise ValueError("OHLC DataFrame is empty")
        
        return True

